// Mock data —

export const SERVICES = [
  {
    id: "s1",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Glow & Glam Studio",
    location: "Maryland City, MD, USA",
    rating: 4.9,
    reviews: 255,
    price: 499,
    originalPrice: 699,
    duration: 90,
    image:
      "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=280&fit=crop",
    description:
      "Full hair coloring service with premium products. Includes consultation, coloring, and blowout.",
    stylist: "Sofia Martinez",
    stylistAvatar: "https://i.pravatar.cc/48?img=47",
  },
  {
    id: "s2",
    name: "Hair Spa",
    category: "Hair Spa",
    salon: "The Velvet Touch",
    location: "New Jersey, USA",
    rating: 4.7,
    reviews: 180,
    price: 569,
    originalPrice: 699,
    duration: 60,
    image:
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=280&fit=crop",
    description:
      "Luxurious hair spa treatment for deep nourishment and shine restoration.",
    stylist: "Priya Shah",
    stylistAvatar: "https://i.pravatar.cc/48?img=31",
  },
  {
    id: "s3",
    name: "Hair Cut",
    category: "Hair Cut",
    salon: "Aura Luxe Salon",
    location: "California, USA",
    rating: 4.5,
    reviews: 120,
    price: 399,
    originalPrice: 699,
    duration: 45,
    image:
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=280&fit=crop",
    description:
      "Precision haircut by expert stylists. Includes wash, cut, and style.",
    stylist: "James Lee",
    stylistAvatar: "https://i.pravatar.cc/48?img=12",
  },
  {
    id: "s4",
    name: "Makeup",
    category: "Makeup",
    salon: "Opal Beauty Lounge",
    location: "Maryland, USA",
    rating: 4.8,
    reviews: 310,
    price: 749,
    originalPrice: 999,
    duration: 75,
    image:
      "https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=400&h=280&fit=crop",
    description: "Professional makeup for events, weddings, and photoshoots.",
    stylist: "Aisha Patel",
    stylistAvatar: "https://i.pravatar.cc/48?img=45",
  },
  {
    id: "s5",
    name: "Nails",
    category: "Nails",
    salon: "The Glam Society",
    location: "Texas, USA",
    rating: 4.2,
    reviews: 95,
    price: 459,
    originalPrice: 699,
    duration: 50,
    image:
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=280&fit=crop",
    description: "Gel, acrylic, or classic nail art with premium products.",
    stylist: "Tanya Brown",
    stylistAvatar: "https://i.pravatar.cc/48?img=22",
  },
  {
    id: "s6",
    name: "Hair Cut",
    category: "Hair Cut",
    salon: "Crown & Curl",
    location: "Texas, USA",
    rating: 4.9,
    reviews: 420,
    price: 699,
    originalPrice: 699,
    duration: 60,
    image:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=400&h=280&fit=crop",
    description:
      "Premium barbershop experience. Classic cuts, fades, and beard trims.",
    stylist: "Marcus King",
    stylistAvatar: "https://i.pravatar.cc/48?img=7",
  },
  {
    id: "s7",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Élan Beauty Bar",
    location: "New Jersey, USA",
    rating: 4.6,
    reviews: 165,
    price: 499,
    originalPrice: 699,
    duration: 90,
    image:
      "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=400&h=280&fit=crop",
    description:
      "Balayage, highlights, and full color services with Kerastase products.",
    stylist: "Elena Russo",
    stylistAvatar: "https://i.pravatar.cc/48?img=38",
  },
  {
    id: "s8",
    name: "Hair Color",
    category: "Hair Color",
    salon: "The Polished Room",
    location: "Alabama, USA",
    rating: 4.5,
    reviews: 88,
    price: 569,
    originalPrice: 699,
    duration: 75,
    image:
      "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=400&h=280&fit=crop",
    description: "Color correction, toning, and glossing services.",
    stylist: "Rachel Kim",
    stylistAvatar: "https://i.pravatar.cc/48?img=41",
  },
  {
    id: "s9",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Noir Luxury Salon",
    location: "Washington, DC, USA",
    rating: 4.2,
    reviews: 73,
    price: 399,
    originalPrice: 699,
    duration: 90,
    image:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=400&h=280&fit=crop",
    description: "Luxury hair coloring in an upscale studio environment.",
    stylist: "Dominique Bernard",
    stylistAvatar: "https://i.pravatar.cc/48?img=48",
  },
  {
    id: "s10",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Blush & Gold Studio",
    location: "Montana, USA",
    rating: 4.0,
    reviews: 55,
    price: 399,
    originalPrice: 699,
    duration: 80,
    image:
      "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400&h=280&fit=crop",
    description: "Warm-toned color specialists. Copper, golden, and rose hues.",
    stylist: "Amber Collins",
    stylistAvatar: "https://i.pravatar.cc/48?img=27",
  },
  {
    id: "s11",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Allure Unisex Studio",
    location: "Virginia, USA",
    rating: 4.3,
    reviews: 112,
    price: 419,
    originalPrice: 699,
    duration: 90,
    image:
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=280&fit=crop",
    description: "Full-service unisex salon for all hair types and textures.",
    stylist: "Chris Morgan",
    stylistAvatar: "https://i.pravatar.cc/48?img=15",
  },
  {
    id: "s12",
    name: "Hair Color",
    category: "Hair Color",
    salon: "Urban Blend",
    location: "Alabama, USA",
    rating: 4.1,
    reviews: 67,
    price: 299,
    originalPrice: 699,
    duration: 75,
    image:
      "https://images.unsplash.com/photo-1559599101-f09722fb4948?w=400&h=280&fit=crop",
    description: "Affordable color services without compromising quality.",
    stylist: "Kevin Mills",
    stylistAvatar: "https://i.pravatar.cc/48?img=5",
  },
];

export const CATEGORIES = [
  "All",
  "Hair Cut",
  "Hair Color",
  "Hair Spa",
  "Makeup",
  "Nails",
];

export const STYLISTS = [
  { id: "st1", name: "Sofia Martinez", specialty: "Color Specialist" },
  { id: "st2", name: "James Lee", specialty: "Precision Cuts" },
  { id: "st3", name: "Priya Shah", specialty: "Hair Spa & Treatment" },
  { id: "st4", name: "Marcus King", specialty: "Barbering" },
];

export const TIME_SLOTS = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "01:00 PM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
  "04:30 PM",
  "05:00 PM",
  "05:30 PM",
  "06:00 PM",
];

// Slots that are "booked" — in production this comes from the API
export const BOOKED_SLOTS = ["09:30 AM", "11:00 AM", "02:00 PM", "04:30 PM"];

export const MOCK_BOOKINGS = [
  {
    id: "b1",
    service: "Hair Cut",
    salon: "Glow & Glam Studio",
    ref: "R123",
    status: "completed",
    date: "Tue 30 Sep",
    time: "7:30 PM",
    totalPaid: 459,
    image:
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=80&h=80&fit=crop",
  },
  {
    id: "b2",
    service: "Hair Color",
    salon: "Élan Beauty Bar",
    ref: "R124",
    status: "completed",
    date: "Mon 22 Sep",
    time: "3:00 PM",
    totalPaid: 499,
    image:
      "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=80&h=80&fit=crop",
  },
  {
    id: "b3",
    service: "Hair Cut",
    salon: "Crown & Curl",
    ref: "R125",
    status: "canceled",
    date: "Tue 30 Sep",
    time: "7:30 PM",
    totalPaid: 459,
    image:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=80&h=80&fit=crop",
  },
  {
    id: "b4",
    service: "Hair Spa",
    salon: "The Velvet Touch",
    ref: "R126",
    status: "canceled",
    date: "Tue 30 Sep",
    time: "7:30 PM",
    totalPaid: 459,
    image:
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=80&h=80&fit=crop",
  },
  {
    id: "b5",
    service: "Makeup",
    salon: "Opal Beauty Lounge",
    ref: "R127",
    status: "pending",
    date: "Sat 4 Oct",
    time: "11:00 AM",
    totalPaid: 749,
    image:
      "https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=80&h=80&fit=crop",
  },
  {
    id: "b6",
    service: "Nails",
    salon: "The Glam Society",
    ref: "R128",
    status: "pending",
    date: "Fri 3 Oct",
    time: "2:00 PM",
    totalPaid: 459,
    image:
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=80&h=80&fit=crop",
  },
  {
    id: "b7",
    service: "Hair Color",
    salon: "Noir Luxury Salon",
    ref: "R129",
    status: "pending",
    date: "Thu 2 Oct",
    time: "10:00 AM",
    totalPaid: 399,
    image:
      "https://images.unsplash.com/photo-1633681122188-2c43a18b3c34?w=80&h=80&fit=crop",
  },
];
